### ISSUE TITLE
Pause while on battery [not only "low on battery"]?

### ISSUE THREAD

**Issue by jucor** [thenewinquiry/bailbloc#24]
Dear BailBloc team

BailBloc is a brilliant idea! I've noticed the setting to "Pause when low on battery". Is there a way to either, from the most lenient to the more stringent:
1.  set the "low" level to other than the current 50%.
1. "pause  when on battery, regardless of the load charge"
1. "pause when not fully charged, even if plugged in" (my personal preference, and the easiest to implement: set the level to 100%)

I suspect many laptop users might not be able to run BailBlock it if it halves their battery life, and will forget to fire it when plugging in. Some might also want to only mine when fully charged, to not slow down the charging time.

**Comment by jucor** [comment]
I believe the modifications would be needed in that part of the code:
https://github.com/thenewinquiry/bailbloc/blob/6888e454bd35affdb37635a9e4238fdcf6f415a7/desktop/main.js#L80

**Comment by antiboredom** [comment]
Hi! Yes we need to address this - It’s been confusing for users, and your suggestions are good ones. I’ll take a look for the next release...

**Comment by fivetonsflax** [comment]
I came here to ask for #3 myself. Thank you, @jucor, for expressing it so well that I didn't have to. Like Julien, I want to mine only when I'm plugged in and at 100% charge.

Thank you.
