### ISSUE TITLE
Flagged as a virus by AVG on macbook

### ISSUE THREAD

**Issue by datesss** [thenewinquiry/bailbloc#25]
Hi!
This is not really a 'bug' that you can fix, but something i thought u should be aware of, and maybe make a note of in the documentation.
 
When i went to install, AVG automatically quarantined the miner binary, breaking the install. For less technical users, this could freak them out or be an issue.

![screen shot 2017-11-16 at 14 29 49](https://user-images.githubusercontent.com/9736319/32911829-58d4e3f0-cadb-11e7-8415-272cb7a89dbb.png)

Macbook Pro
AVG info:
Version 17.4 (9cf9975e9ca8)
Virus databases: 171116-10
Last update: November 16, 2017

**Comment by antiboredom** [comment]
Hi - yes there's nothing much we can do about that - although it's interesting that it flagged the linux binary rather than the osx one. We'll make a note on the website. Thanks!
