### ISSUE TITLE
add info for macOS installation process

### ISSUE THREAD

**Issue by prismspecs** [thenewinquiry/bailbloc#3]
indicate to users on the 'drag to applications folder' page that they'll actually have to open the app for it to start working, and/or indicate that it's in their toolbar upon opening (maybe you do? I re-installed and didn't see this).

**Comment by antiboredom** [comment]
hmm - i'm looking into a way to automatically install and run for both mac and windows...

**Comment by antiboredom** [comment]
I think the only way to do this is to switch from a dmg to a pkg (with an install window). Do we think that's a good idea? If not we could include written instruction in the background of the dmg...

**Comment by prismspecs** [comment]
i think instructions in the background is fine

**Comment by antiboredom** [comment]
here's what I got - let me know if it's alright:

![image](https://user-images.githubusercontent.com/344861/32259657-53f23d1e-be98-11e7-9eae-c4b2557adab2.png)
