### ISSUE TITLE
showing -1 active users

### ISSUE THREAD

**Issue by akilism** [thenewinquiry/bailbloc#41]
![screen shot 2017-12-05 at 9 48 23 am](https://user-images.githubusercontent.com/1005167/33613049-877c5cc2-d9a1-11e7-8a7e-1b4e539ca62d.png)

**Comment by rubinovitz** [comment]
@akilism Thanks for the heads up! We believe this is a result of the external pool API we use to aggregate this data going down, so we will see if this corrects itself now that the pool API is back up. Either way an error message showing that's what is going on would be nice here. 

Thanks again!

-JB
