### ISSUE TITLE
"Run Bail Bloc" toggle option does not work

### ISSUE THREAD

**Issue by duyatran** [thenewinquiry/bailbloc#49]
Thank you for your work. As titled, the toggle option "Run Bail Bloc" in the context menu would turn off the miner for 3 seconds, before turning it on again. A quick look at main.js seems to suggest that the issue is due to checkCharging() calling startMining() again after 3 seconds. Maybe set another variable in toggleMiner and check it in the else if clause of checkCharging?

**Comment by wgwz** [comment]
i can verify that this is happening for me as well.
