### ISSUE TITLE
Mining code update needed before the march monero update

### ISSUE THREAD

**Issue by moneromooo** [thenewinquiry/bailbloc#54]
Monero will be tweaking its PoW algorithm in the next fork, in order to strengthen its ASIC resistance and keep CPU miners competitive.

I notice you're using xmrig internally, and I made a patch for this here: https://github.com/xmrig/xmrig-nvidia/pull/105

You will need to update xmrig once they've merged this in order to be able to continue mining monero after the march update. This should be the only thing that needs to change for you.

**Comment by prismspecs** [comment]
thanks!
