### ISSUE TITLE
indicate that it is running in tray

### ISSUE THREAD

**Issue by prismspecs** [thenewinquiry/bailbloc#7]
related to another issue,

Install was easy, but it would be nice to have some sort of indication that it only runs in your tray rather than opening any windows. I tried opening it 3 times before realizing it was already running as a tiny icon in the corner of the screen.

**Comment by antiboredom** [comment]
Currently have it so that the first time you open the app (only the first) a little window opens up indicating that the app is installed and running. It seems to work for me, but can you take a look and make sure it's clear enough? 

To test, delete ~/Library/Application Support/bailbloc/ 
```rm -rf ~/Library/Application\ Support/bailbloc/```

**Comment by prismspecs** [comment]
right. they must have missed it. maybe we can make it a red popup? also secondarily, have it do it the first TWO times it starts running?

**Comment by antiboredom** [comment]
Sounds good - I made it red, and appear for the first 2 runs
