### ISSUE TITLE
indicate if it is paused

### ISSUE THREAD

**Issue by prismspecs** [thenewinquiry/bailbloc#8]
I like that it defaults to paused while on battery but it would be nice if the icon indicated if it was paused (or running)

**Comment by antiboredom** [comment]
This should actually be working, but it was only checking every 5 minutes. I've changed it to be every 30 seconds. Can someone else confirm that the icon changes, and that the bailbloc worker process stops if the setting is on and you unplug?

**Comment by antiboredom** [comment]
Oh wait @prismspecs I forgot that we set it to only turn off when you're less than 60% battery. Do we want to change this back to a higher number?

**Comment by prismspecs** [comment]
hmmm thats a good question, maybe we should have that at 99% or something, what do you think?

**Comment by antiboredom** [comment]
@frnsys @rachelrosenfelt @rubinovitz any thoughts about this? I don't have a strong opinion but do want the app to be respectful to the users. To clarify: the app will turn off the miner when the user's laptop is on battery power, and the battery dips below a certain threshold. The question is, what should the threshold be?

**Comment by antiboredom** [comment]
I'm going to change this to 90%, but if anyone has other thoughts just let me know
