### ISSUE TITLE
uninstall process?

### ISSUE THREAD

**Issue by prismspecs** [thenewinquiry/bailbloc#9]
The only thing that was a little creepy: tried to deinstall but couldn't because it was running, but didn't know how to turn it off without deinstalling it

**Comment by antiboredom** [comment]
This is a bit tough - we could maybe just include some instructions - it'll be just the normal uninstall process for mac/windows.

**Comment by antiboredom** [comment]
(also there's a quit item in the menu)

**Comment by prismspecs** [comment]
yeah maybe this is excessive
